PROVINATUS_ULTIMATES_BY_INDEX = {
  [1] = {name = "Dragonknight Standard"},
  [2] = {name = "Shifting Standard"},
  [3] = {name = "Standard of Might"},
  [4] = {name = "Dragon Leap"},
  [5] = {name = "Take Flight"},
  [6] = {name = "Ferocious Leap"},
  [7] = {name = "Magma Shell"},
  [8] = {name = "Magma Armor"},
  [9] = {name = "Corrosive Armor"},
  [10] = {name = "Death Stroke"},
  [11] = {name = "Incapacitating Strike"},
  [12] = {name = "Soul Harvest"},
  [13] = {name = "Consuming Darkness"},
  [14] = {name = "Bolstering Darkness"},
  [15] = {name = "Veil of Blades"},
  [16] = {name = "Soul Shred"},
  [17] = {name = "Soul Siphon"},
  [18] = {name = "Soul Tether"},
  [19] = {name = "Summon Storm Atronach"},
  [20] = {name = "Greater Storm Atronach"},
  [21] = {name = "Summon Charged Atronach"},
  [22] = {name = "Negate Magic"},
  [23] = {name = "Suppression Field"},
  [24] = {name = "Absorption Field"},
  [25] = {name = "Overload"},
  [26] = {name = "Power Overload"},
  [27] = {name = "Energy Overload"},
  [28] = {name = "Aedric Spear"},
  [29] = {name = "Radial Sweep"},
  [30] = {name = "Empowering Sweep"},
  [31] = {name = "Crescent Sweep"},
  [32] = {name = "Nova", texture = "/esoui/art/icons/ability_templar_nova.dds"},
  [33] = {name = "Solar Prison", texture = "/esoui/art/icons/ability_templar_solar_prison.dds"},
  [34] = {name = "Solar Disturbance", texture = "/esoui/art/icons/ability_templar_solar_disturbance.dds"},
  [35] = {name = "Rite of Passage", texture = "/esoui/art/icons/ability_templar_rite_of_passage.dds"},
  [36] = {name = "Remembrance", texture = "/esoui/art/icons/ability_templar_remembrance.dds"},
  [37] = {name = "Practiced Incantation", texture = "/esoui/art/icons/ability_templar_practiced_incantation.dds"},
  [38] = {name = "Soul Strike"},
  [39] = {name = "Soul Assault"},
  [40] = {name = "Shatter Soul"},
  [41] = {name = "Bat Swarm"},
  [42] = {name = "Clouding Swarm"},
  [43] = {name = "Devouring Swarm"},
  [44] = {name = "Werewolf Transformation"},
  [45] = {name = "Pack Leader"},
  [46] = {name = "Werewolf Berserker"},
  [47] = {name = "Dawnbreaker"},
  [48] = {name = "Flawless Dawnbreaker"},
  [49] = {name = "Dawnbreaker of Smiting"},
  [50] = {name = "Meteor"},
  [51] = {name = "Ice Comet"},
  [52] = {name = "Shooting Star"},
  [53] = {name = "War Horn"},
  [54] = {name = "Aggressive Horn"},
  [55] = {name = "Sturdy Horn"},
  [56] = {name = "Barrier"},
  [57] = {name = "Reviving Barrier"},
  [58] = {name = "Replenishing Barrier"},
  [59] = {name = "Undo"},
  [60] = {name = "Precognition"},
  [61] = {name = "Temporal Guard"}
}

-- Reverse index of ultimates.
PROVINATUS_ULTIMATES_BY_NAME = {
  ["Dragonknight Standard"] = 1,
  ["Shifting Standard"] = 2,
  ["Standard of Might"] = 3,
  ["Dragon Leap"] = 4,
  ["Take Flight"] = 5,
  ["Ferocious Leap"] = 6,
  ["Magma Armor"] = 7,
  ["Magma Shell"] = 8,
  ["Corrosive Armor"] = 9,
  ["Death Stroke"] = 10,
  ["Incapacitating Strike"] = 11,
  ["Soul Harvest"] = 12,
  ["Consuming Darkness"] = 13,
  ["Bolstering Darkness"] = 14,
  ["Veil of Blades"] = 15,
  ["Soul Shred"] = 16,
  ["Soul Siphon"] = 17,
  ["Soul Tether"] = 18,
  ["Summon Storm Atronach"] = 19,
  ["Greater Storm Atronach"] = 20,
  ["Summon Charged Atronach"] = 21,
  ["Negate Magic"] = 22,
  ["Suppression Field"] = 23,
  ["Absorption Field"] = 24,
  ["Overload"] = 25,
  ["Power Overload"] = 26,
  ["Energy Overload"] = 27,
  ["Aedric Spear"] = 28,
  ["Radial Sweep"] = 29,
  ["Empowering Sweep"] = 30,
  ["Crescent Sweep"] = 31,
  ["Nova"] = 32,
  ["Solar Prison"] = 33,
  ["Solar Disturbance"] = 34,
  ["Rite of Passage"] = 35,
  ["Remembrance"] = 36,
  ["Practiced Incantation"] = 37,
  ["Soul Strike"] = 38,
  ["Soul Assault"] = 39,
  ["Shatter Soul"] = 40,
  ["Bat Swarm"] = 41,
  ["Clouding Swarm"] = 42,
  ["Devouring Swarm"] = 43,
  ["Werewolf Transformation"] = 44,
  ["Pack Leader"] = 45,
  ["Werewolf Berserker"] = 46,
  ["Dawnbreaker"] = 47,
  ["Flawless Dawnbreaker"] = 48,
  ["Dawnbreaker of Smiting"] = 49,
  ["Meteor"] = 50,
  ["Ice Comet"] = 51,
  ["Shooting Star"] = 52,
  ["War Horn"] = 53,
  ["Aggressive Horn"] = 54,
  ["Sturdy Horn"] = 55,
  ["Barrier"] = 56,
  ["Reviving Barrier"] = 57,
  ["Replenishing Barrier"] = 58,
  ["Undo"] = 59,
  ["Precognition"] = 60,
  ["Temporal Guard"] = 61
}

